name: Build Firmware Action
on: 
  workflow_dispatch:
    branches: 

jobs:
  build:
    
    name: Build DataLogger IoT
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo and submodules
        uses: actions/checkout@v3
        
      - name: Et Tu Submodule
        uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: |
            ${{ secrets.FLUX_PULL_KEY_2 }}
      - run: git submodule update --init --recursive

      - name: Arduino - Install and setup the Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Arduino - Start config file
        run: arduino-cli config init --additional-urls "https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json"

      - name: Arduino - Update index
        run: arduino-cli core update-index

      # Install ESP32 
      - name: Arduino - Install ESP32 platform
        run: arduino-cli core install esp32:esp32

      - name: Install Flux needed libraries.
        run: ./SparkFun_DataLogger/SparkFun_Flux/install_libs.sh

      - name: Arduino - Install *private libraries* - 
        run: |
          arduino-cli lib install --git-url https://github.com/sparkfun/SparkFun_Flux.git
          ls -la
          
      #Incorporate ESP-Now patch into core: https://github.com/espressif/arduino-esp32/pull/7044/files
      #- name: Patch ESP32 Core
      #  run: |
      #    cd Firmware/RTK_Surveyor/Patch/
      #    cp WiFiGeneric.cpp /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.2/libraries/WiFi/src/WiFiGeneric.cpp

      # - name: Compile Sketch
      #   run: arduino-cli compile --fqbn esp32:esp32:esp32 ./Firmware/RTK_Surveyor/RTK_Surveyor.ino
      #     --build-property build.partitions=partitions
      #     --build-property upload.maximum_size=3145728 
      #     --build-property "compiler.cpp.extra_flags=\"-DPOINTPERFECT_TOKEN=$POINTPERFECT_TOKEN\" \"-DFIRMWARE_VERSION_MAJOR=$FIRMWARE_VERSION_MAJOR\" \"-DFIRMWARE_VERSION_MINOR=$FIRMWARE_VERSION_MINOR\" \"-DENABLE_DEVELOPER=${{ env.ENABLE_DEVELOPER }}\""
      #     --export-binaries

      # - name: Rename binary
      #   run: |
      #     cd Firmware/RTK_Surveyor/build/esp32.esp32.esp32/
      #     mv RTK_Surveyor.ino.bin ${{ env.FILENAME_PREFIX }}${{ env.FILE_ENDING_UNDERSCORE }}.bin
